### ISSUE TITLE
Add Labels to Issues

### ISSUE THREAD

**Issue by chris-wolff** [bmdvpanga/tictactoe#11]
@bmdvpanga there doesn't appear to be an option for me to assign labels to issues so other potential contributors can find them. Could you either go through the issues and assign them `beginner-friendly` , `help wanted` , `good first issue`  tags or give me some kind of administrative access to your repo page?

**Comment by bmdvpanga** [comment]
Hi @chris-wolff you should now have the power to assign tags to issues :)
